### ISSUE TITLE
Continuous raster optimisation results in homogenous resistance layer with values of 1

### ISSUE THREAD

**Issue by jamesryan1896** [wpeterman/ResistanceGA#11]
I am running ResistanceGA on Windows 10 in Rstudio, using R version 3.6.1
optimising with Circuitscape v4.0.5. I am using the following code to optimsie;
![code](https://user-images.githubusercontent.com/57244426/77811441-f8126c00-70e5-11ea-811f-7b58f0d413e2.PNG)

I have tried to optimise an elevation raster using the monomolecular transformation however the resulting transformation at the end looks like this;
![transformation](https://user-images.githubusercontent.com/57244426/77811544-c4841180-70e6-11ea-94be-76266a8e1aaf.PNG)

It is ends up with an almost identical AIC value and a slighty worse AICc value than the distance model, presumably because it becomes the same layer with additional k parameters. Do you know why I may be gettig such an output rather than something that more closely follows the transfomation I tried to apply?

The raster I am using looks like this;
![raster](https://user-images.githubusercontent.com/57244426/77811713-f47fe480-70e7-11ea-8ce0-d7a436b51b1b.PNG)

Thank you for taking the time to read my issue,
James

**Comment by wpeterman** [comment]
Hi James--

Two thoughts. First, make sure that all of your sample points are within your landscape. It appears from the image that one point in the SE may be outside the boundary. Use the `extract` function from the raster package.

Second, it may be that isolation by distance is the process shaping genetic differentiation on your landscape. Assuming the optimization worked correctly, and it appears that it has, then the IBD model by itself is best supported as a simpler model than optimizing the elevation resistance surface to IBD.

**Comment by jamesryan1896** [comment]
Ah sometimes Rstudio just positions my points off the raster even though they are definitely within the extent. You are correct, it did work perfectly and I understand where I've gone wrong, just needed to do some more investigating. Thank you for your time!
