### ISSUE TITLE
 Optimization problems

### ISSUE THREAD

**Issue by AridaiHari** [wpeterman/ResistanceGA#12]
Hello, 
I used the code below for optimization with the GA package , but I have been getting errors.

dir.create(file.path("./Optimized"))
dir.create(file.path("./Optimized", "07042020"))        
write.dir <- "./Optimized/07042020"

#Optimization 
GA.inputs_All <- GA.prep(method = "AIC", ASCII.dir = CVM, 
                         Results.dir = write.dir, 
                         min.cat = 0,   
                         select.trans = list("A", NA , "A", "A", "A", "A", NA, "A", "A", "A", "A", "A"), 
                         parallel = 4) 

And it produces this warning:

Warning message:
In dir.create(file.path(Results.DIR, "Plots")) :
  cannot create dir '.\Optimized\07042020Results\\Plots', reason 'No such file or directory' 

the code creates 07042020, Results and tmp directories but not Plots. 

I hope I can have an answer. Thank you!

**Comment by wpeterman** [comment]
Not certain, but I might suggest specifying the full directory rather than
a relative path to your write.dir. This ultimately shouldn't matter, but
may be the issue in this case.



*Bill Peterman *Assistant Professor
School of Environment and Natural Resources
The Ohio State University
2021 Coffey Road
Columbus, OH 43210-1085
Phone: 614.292.9795
Web Page <https://goo.gl/4Gc15W>
Terrestrial Wildlife Ecology Lab <http://www.twel.osu.edu>

**Comment by AridaiHari** [comment]
Actually I tried the complete path but the error is still the same 

CVM<-stack("C:/Users/Gabriela/Documents/CutByLadera/CVM_stack.tif")
dir.create(file.path("C:/Users/Gabriela/Documents/CutByLadera/Optimized"))
dir.create(file.path("C:/Users/Gabriela/Documents/CutByLadera/Optimized", "07042020"))        

write.dir <- "C:/Users/Gabriela/Documents/CutByLadera/Optimized/07042020"

GA.inputs_All <- GA.prep(method = "AIC", ASCII.dir = CVM, 
                         Results.dir = write.dir, 
                         min.cat = 0,   
                         select.trans = list("A", NA , "A", "A", "A", "A", NA, "A", "A", "A", "A", "A"), 
                         parallel = 4) 

Warning message:
In dir.create(file.path(Results.DIR, "Plots")) :
  cannot create dir 'C:\Users\Gabriela\Documents\CutByLadera\Optimized\07042020Results\\Plots', reason 'No such file or directory'

**Comment by wpeterman** [comment]
Specify the full path, ending with a forward slash.
write.dir <- "C:/Users/Gabriela/Documents/CutByLadera/Optimized/07042020/"



*Bill Peterman *Assistant Professor
School of Environment and Natural Resources
The Ohio State University
2021 Coffey Road
Columbus, OH 43210-1085
Phone: 614.292.9795
Web Page <https://goo.gl/4Gc15W>
Terrestrial Wildlife Ecology Lab <http://www.twel.osu.edu>

Bill Peterman

**Comment by AridaiHari** [comment]
Thanks!!!! :) :)
