### ISSUE TITLE
Issue in Namespace

### ISSUE THREAD

**Issue by amandamancini** [wpeterman/ResistanceGA#15]
I am getting the following error message when I try to load ResistanceGA using devtools:
`─  installing *source* package ‘ResistanceGA’ ...`
`   ** using staged installation`
`   ** R`
`   ** data`
`   *** moving datasets to lazyload DB`
`   ** inst`
`   ** byte-compile and prepare package for lazy loading`
`   Error: object ‘as.im’ is not exported by 'namespace:spatstat'`
`   Execution halted`
`   ERROR: lazy loading failed for package ‘ResistanceGA’`
`─  removing ‘/tmp/RtmptgrOQq/Rinst66be1001b348/ResistanceGA’`
`         -----------------------------------`
`   ERROR: package installation failed`
`Error: Failed to install 'ResistanceGA' from GitHub:`
`  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):`
`E> ** data`
`E> *** moving datasets to lazyload DB`
`E> ** inst`
`E> ** byte-compile and prepare package for lazy loading`
`E> Error: object ‘as.im’ is not exported by 'namespace:spatstat'`
`E> Execution halted`
`E> ERROR: lazy loading failed for package ‘ResistanceGA’`
`E> * removing ‘/tmp/RtmptgrOQq/Rinst66be1001b348/ResistanceGA’`
`E>       -----------------------------------`
`E> ERROR: package installation failed`

The major issues seems to be the error: object ‘as.im’ is not exported by 'namespace:spatstat'. spatstat was just uploaded on 3/13/21 so maybe that is part of the issue. It looks like in the namespace ResistanceGA is calling the following:
`importFrom(spatstat, as.im)`
`importFrom(spatstat, as.matrix.im)`
`importFrom(spatstat, blur)`

However, those objects are not exported from spatstat in the namespace, but rather spatstat.geom and spatstat.core. Perhaps the following changes would fix the error:
`importFrom(spatstat.geom, as.im)`
`importFrom(spatstat.geom, as.matrix.im)`
`importFrom(spatstat.core, blur)`

I will also submit a pull request with the above changes, but if this is not the solution do you have any suggestions with how to fix this issue?

**Comment by amandamancini** [comment]
I forked the repo and ran the changes and this seemed to fix the issue. I submitted a pull request with the modifications.

**Comment by amandamancini** [comment]
I forked the repo and ran the changes and this seemed to fix the issue. I submitted a pull request with the modifications.

**Comment by FAmorim81** [comment]
Hi @amandamancini,

I'm running into the same issue. Could you provide me some extra information on how you solved it?

Cheers
