### ISSUE TITLE
Output diagnostic plots only to directory not screen

### ISSUE THREAD

**Issue by EveTC** [wpeterman/ResistanceGA#18]
Hello,

Thank you for this package - it is exactly what I was looking for!

I am running ResistanceGA on a server screen. I would like to output diagnostic plots but I kept recieveing an X11 error, as it can not plot directly to my computer when I leave the screen and let ResistanceGA continue running on the server.

I then added `diagnostic_plots=FALSE` which allows me to complete the iterations but it now doesnt output any diagnostic plots. I may have missed something, so my apologies if I have, but is there a way to output the diagnostic plots to only the directory?

Thank you in advance.
Eve

**Comment by wpeterman** [comment]
The `diagnostic_plots = FALSE` was added to circumvent this issue. I don't work enough with servers to fully understand the alternatives to this. However, you can recreate all the diagnostic plots yourself after a completed optimization using the `Diagnostic.Plots` function with the files created from during the optimization.

**Comment by EveTC** [comment]
Ok fantastic, thank you for your help
