### ISSUE TITLE
Error in SS_optim.scale(jl.inputs = jl.inp, GA.inputs = GA.inp) :    could not find function "SS_optim.scale"

### ISSUE THREAD

**Issue by KarenCox** [wpeterman/ResistanceGA#23]
Hello,

I have installed the latest version of ResistanceGA, but for some reason the function SS_optim.scale is not recognised. I tried to circumvent the problem by sourcing the function. However, this entailed that other functions  (e.g. MLPE.R, k_smooth.R, ...) and libraries (such as GA and MuMin) had to be loaded as well to avoid getting errors along the way. Should I install a different version? Hope you can help me out.

Karen

**Comment by wpeterman** [comment]
Hi Karen--

I have largely discontinued support of the `.scale` optimization options. The functions are still there, but I make no guarantees of their integration within the package nor the outputs produced. If you want to use it, try:
`ResistanceGA:::SS_optim.scale(jl.inputs = jl.inp, GA.inputs = GA.inp)`

**Comment by KarenCox** [comment]
Thank you for your quick response.  Does this mean that for instance in the all_comb option the results of the scale optimisation are not necessarily correct?

**Comment by wpeterman** [comment]
It looks like `all_comb` isn't going to work right now, but that's because of an issue with the `MS_optim.scale` function. As I said, I haven't been maintaining the scale functions for quite some time now. I will see if there is an easy fix and push an update soon, if possible.

**Comment by seanvanderluit** [comment]
Hi there,
Are there any updates on this fix for all_comb?
Thanks!

**Comment by wpeterman** [comment]
the `all_comb` function itself works, just not in conjunction with the no longer supported or maintained `.scale` functions.
