### ISSUE TITLE
Error in { :    task 1 failed - "arguments imply differing number of rows: 7, 12"

### ISSUE THREAD

**Issue by hannehaug** [wpeterman/ResistanceGA#28]
Hi,
I get this error message when trying to run the "MS_optim" command using jl.prep (julia):
Error in { :    task 1 failed - "arguments imply differing number of rows: 7, 12"

The SS_optim works fine using the same settings, except  including one raster at the time. 
Does anyone have any suggestions on how to solve it or work around it?

**Comment by wpeterman** [comment]
Not sure. `SS_optim` works correctly for all included layers? These problems can be hard to troubleshoot from errors, but I can usually give insight rather quickly is you're willing/able to send the data you're working with (peterman.73@osu.edu)

**Comment by hannehaug** [comment]
Hi!
Yes, SS_optim worked with the included layers. I will send you the data on your email.
Many thanks!

**Comment by wpeterman** [comment]
This issue should be resolved with version 4.2-8
