### ISSUE TITLE
package ‘spatstat.core’ is not available

### ISSUE THREAD

**Issue by petrikemppainen** [wpeterman/ResistanceGA#31]
When installing: "package ‘spatstat.core’ is not available for this version of R"

According to their website:

"The package spatstat.core will be replaced by two packages, spatstat.explore and spatstat.model."

Any suggestions?
Thanks!

**Comment by wpeterman** [comment]
Thanks for notifying me of this. I've updated the package imports to address this change. Get `ResistanceGA 4.2-9` from GitHub.
