### ISSUE TITLE
Still problem with spatstat.core

### ISSUE THREAD

**Issue by petrikemppainen** [wpeterman/ResistanceGA#32]
Getting this one now instead.

 Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
     there is no package called ‘spatstat.core’

Thanks!
/Petri

**Comment by wpeterman** [comment]
Removed use of `spat.core`. Should be good now. Thanks for bringing this up
