### ISSUE TITLE
How to predict a future scenario resistance surface based on a fitted model/parameter ?

### ISSUE THREAD

**Issue by willright28** [wpeterman/ResistanceGA#34]
Hi @wpeterman ,

I'd like to ask a question of how to predict the resistance surface of a given future scenario (e.g., the climatic condition under 2050 RCP5.8) based on a fitted model, which was built by the current climatic condition. The purpose of doing this is to compare the difference of connectivity between the two periods. So, a key point is that it's important to make sure to apply the exact same optimization standard to both layers (i.e., follow the same equation), considering that the climate conditions will change in the future. Is it possible to do that?
To be specify, I' ve transformed a climate layer to a resistance surface using the function 'GA.prep'. Then in the output result folder there was a file named ContinuousResults.csv, which seemed to have the parameters generated by the fitting process(i.e., "Equation","shape","max"). So I wanna ask:
1) Could I use the parameters to construct the resistance surface for future conditions with respect to my main deman?

Thanks for your time and look forward to hearing from you!

Best wishes,
willright28

**Comment by wpeterman** [comment]
Yes. You can do this using the `Combine_Surfaces` function. You just need to specify `PARM`, gdist_/jl_inputs, and `GA.inputs`. For each surface, you need to specify the equation, shape, and max values. You can translate the equations to numeric values:

<html>
<body>


  | 1 = "Inverse-Reverse Monomolecular"
-- | --
  | 2 = "Inverse-Reverse Ricker"
  | 3 = "Monomolecular"
  | 4 = "Ricker"
  | 5 = "Reverse Monomolecular"
  | 6 = "Reverse Ricker"
  | 7 = "Inverse Monomolecular"
  | 8 = "Inverse Ricker"
  | 9 = "Distance"


</body>
</html>

The example below would apply the Inverse-Reverse Monomolecular transformation with a shape of 2 and a maximum value of 25.
`Combine_Surfaces(PARM = c(1, 2, 25),
                              jl.inputs = jl_inputs, 
                              GA.inputs = GA_inputs)`

**Comment by willright28** [comment]
Thanks for every details，it's solved my questuon.



---Original---
From: "Bill ***@***.***&gt;
Date: Sun, Apr 23, 2023 21:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wpeterman/ResistanceGA] How to predict a future scenarioresistance surface based on a fitted model/parameter ? (Issue #34)




 
Yes. You can do this using the Combine_Surfaces function. You just need to specify PARM, gdist_/jl_inputs, and GA.inputs. For each surface, you need to specify the equation, shape, and max values. You can translate the equations to numeric values:
    &nbsp; 1 = "Inverse-Reverse Monomolecular" 
    &nbsp; 2 = "Inverse-Reverse Ricker" 
  &nbsp; 3 = "Monomolecular" 
  &nbsp; 4 = "Ricker" 
  &nbsp; 5 = "Reverse Monomolecular" 
  &nbsp; 6 = "Reverse Ricker" 
  &nbsp; 7 = "Inverse Monomolecular" 
  &nbsp; 8 = "Inverse Ricker" 
  &nbsp; 9 = "Distance" 
   
The example below would apply the Inverse-Reverse Monomolecular transformation with a shape of 2 and a maximum value of 25.
 Combine_Surfaces(PARM = c(1, 2, 25), jl.inputs = jl_inputs,  GA.inputs = GA_inputs)
