### ISSUE TITLE
Error: Failed to install 'ResistanceGA' from GitHub:   ! System command 'Rcmd.exe' failed

### ISSUE THREAD

**Issue by yuhaoran666** [wpeterman/ResistanceGA#35]
![image](https://github.com/wpeterman/ResistanceGA/assets/129647622/d385c836-5aec-4d67-899f-c08b5935f49c)

**Comment by wpeterman** [comment]
Try installing without the vignettes
`build_vignettes = FALSE`

**Comment by yuhaoran666** [comment]
Dear&nbsp;wpeterman，
Thanks to you, I successfully installed ResistanceGA.&nbsp;
I want to know how to create a sampling point that matches my spatial raster data for GA model operation.&nbsp;
I'm trying to optimize multiple drag factors, forming a new composite drag surface.Step (3) how to create samlpe.locales
&nbsp;
&nbsp;best wishes to you.
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, May 18, 2023 05:06 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [wpeterman/ResistanceGA] Error: Failed to install 'ResistanceGA' from GitHub:   ! System command 'Rcmd.exe' failed (Issue #35)

&nbsp;



 
Try installing without the vignettes
 build_vignettes = FALSE

**Comment by yuhaoran666** [comment]
Dear&nbsp;wpeterman,
I do not understand what gdist.inputs is used for, and the meaning of PARM is the same question. Is the point data equivalent to the ecological source of birds in my research? Teacher, I want to know if I just want to optimize multiple resistance surfaces, do I need to use this code?
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, May 18, 2023 05:06 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [wpeterman/ResistanceGA] Error: Failed to install 'ResistanceGA' from GitHub:   ! System command 'Rcmd.exe' failed (Issue #35)

&nbsp;



 
Try installing without the vignettes
 build_vignettes = FALSE

**Comment by wpeterman** [comment]
[ResistanceGA.pdf](https://github.com/wpeterman/ResistanceGA/files/11510130/ResistanceGA.pdf)
[Julia_Guide.pdf](https://github.com/wpeterman/ResistanceGA/files/11510165/Julia_Guide.pdf)
[GettingStarted.pdf](https://github.com/wpeterman/ResistanceGA/files/11510166/GettingStarted.pdf)

Linked above are the vignette documents. Working through these should help your understanding of the method and process.

**Comment by yuhaoran666** [comment]
Thanks for your help, I've tried to compile the code myself, but I've run into a problem, my code keeps reporting an error at this step gdist.response <- Run_gdistance(gdist.inputs = gdist.inputs,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;r = Resist)
The result shows -99999 and I don't know how to fix it. Additionally, I have four resistance surfaces (three continuous variables, one categorical) that need to be optimized into one final composite resistance surface, so setting PARM <- c(3, 29, 1, 11, 0, 211, 0, 60), I don't know if this is causing my gdist.response to get wrong results

------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, May 19, 2023 01:53 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [wpeterman/ResistanceGA] Error: Failed to install 'ResistanceGA' from GitHub:   ! System command 'Rcmd.exe' failed (Issue #35)

&nbsp;



 
ResistanceGA.pdf
 Julia_Guide.pdf
 GettingStarted.pdf
 
Linked above are the vignette documents. Working through these should help your understanding of the method and process.

**Comment by yuhaoran666** [comment]
Dear Peterman,
When I use the ResistanceGA package to optimize 6 continuous variables to become a resistance surface, their minimum value is 0 and the maximum value is 1. When I use PARM to set the parameters, it has been wrong, which leads to my Resist <- Combine_Surfaces( PARM = PARM,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; gdist.inputs = gdist.inputs,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; GA.inputs = GA.inputs,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; out = NULL,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; rescale = TRUE)


plot(Resist, main = "scaled composite resistance")##The pictures show invalid values, please help me, I have been researching for two weeks, and I am a beginner in R language. Thanks for your help, much appreciated

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, May 19, 2023 01:53 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [wpeterman/ResistanceGA] Error: Failed to install 'ResistanceGA' from GitHub:   ! System command 'Rcmd.exe' failed (Issue #35)

&nbsp;



 
Closed #35 as completed.
