### ISSUE TITLE
Output write error

### ISSUE THREAD

**Issue by pdchnsky** [wpeterman/ResistanceGA#36]
Hello,

I am running a ResistanceGA analysis and I have gotten an error stating that the output cannot write to the output dataframe. The error states that there is an incorrect number of rows after the analysis has run. I have attached an image of the truncated output.

![image](https://github.com/wpeterman/ResistanceGA/assets/89862962/c6049f15-1d24-4cc1-89f3-ba168d264538)

I am using R v4.2.2, Julia v1.8.5, proj v6.3.1, geos v3.11.1 and gdal v3.6.1 all build with gcc 9. I used Circuitscape v5.12.3. ResistanceGA is v4.2.8 and it uses raster v3.6.20 and sp v1.6.0. It's running on an x86_64-pc-linux-gnu platform with a CentOS Linux 7 core. My inputs are as follows:

```
sp.dat <- readRDS("spat.rds")
cont.rast <- c("ASCII/")
gen.dist <- readRDS("gend.rds")

GA.inputs <- GA.prep(ASCII.dir = cont.rast, Results.dir = "results/")
jl.inputs <- jl.prep(n.Pops = length(sp.dat), response = lower(gen.dist), CS_Point.File = sp.dat, JULIA_HOME = JULIA_HOME
jl.optim <- SS_optim(jl.inputs = jl.inputs, GA.inputs = GA.inputs)
```

There are outputs, but some of them don't have information in them.

<img width="874" alt="image" src="https://github.com/wpeterman/ResistanceGA/assets/89862962/14e50200-0af7-4b23-953e-309b40eec174">
<img width="872" alt="image" src="https://github.com/wpeterman/ResistanceGA/assets/89862962/11e92234-3ffe-4574-95c5-183b854f9f3f">

Thank you!

**Comment by wpeterman** [comment]
I'm not sure what would be causing this issue. I typically read in all raster layers and pass these as an object, rather than point to the directory where the .asc files reside. If you continue to experience issues, I can take a closer look if you are able to share files.

**Comment by pdchnsky** [comment]
The single surface analysis works when I read in an .asc file to a raster layer object and I only have one raster layer in the analysis stack. Thank you for the feedback.
