### ISSUE TITLE
Analysis stuck without progress

### ISSUE THREAD

**Issue by pdchnsky** [wpeterman/ResistanceGA#39]
Hello,
I'm running a multi-surface analysis using the MS_optim function in a script on a computing cluster.
```
GA.inputs <- GA.prep(ASCII.dir = fullmod, Results.dir = "Results/")
jl.inputs <- jl.prep(n.Pops = length(sp.dat), response = lower(gen.dist), CS_Point.File = sp.dat, JULIA_HOME = "/cm/shared/public/apps/julia/1.8.5/bin$
jl.optim <- MS_optim(jl.inputs = jl.inputs, GA.inputs = GA.inputs)
```
I'm running these program versions: 
```
R/4.2.2
julia/1.8.5
proj/6.3.1
geos/3.11.1
gdal/3.6.1-gcc9
```
When I run the analysis it starts without a problem and runs for over a week. When the analysis finishes, it only outputs an .rds file with the GA results. I can look at the standard error output and it appears to run and iterate okay until it starts to repeat reading maps and doesn't seem to be communicating with Circuitscape anymore.

<img width="838" alt="Screen Shot 2023-09-12 at 2 30 46 PM" src="https://github.com/wpeterman/ResistanceGA/assets/89862962/0b0ae415-b001-4b71-9791-dd9940521bf4">

I was running this again after a successful first run. I didn't change the script. Do you have any ideas what might be causing this issue? Thank you!

**Comment by wpeterman** [comment]
This is the first time I've encountered this issue. Is the .rds file
complete so that you can extract your results?

**Comment by pdchnsky** [comment]
The regular output for a successful run includes the files below. There is a diagnostic plots .tiff in the plot folder. The full.rds and .rds files are the same and contain the GA results. 

<img width="963" alt="Screen Shot 2023-09-13 at 12 33 35 PM" src="https://github.com/wpeterman/ResistanceGA/assets/89862962/5c0a107b-d927-4fec-9cc3-d68072d7fd5a">

I'm not sure about the file completeness, these are the only .rds outputs I have gotten for any of the analyses. I have attached screenshots of the .rds file structure from the most recent run.

<img width="815" alt="Screen Shot 2023-09-13 at 1 03 47 PM" src="https://github.com/wpeterman/ResistanceGA/assets/89862962/c0a0a52f-a286-4be7-8318-157cba4d9dd1">
<img width="794" alt="Screen Shot 2023-09-13 at 1 05 12 PM" src="https://github.com/wpeterman/ResistanceGA/assets/89862962/1bf58d67-d1af-4372-9a7f-23cd2294efa6">
<img width="802" alt="Screen Shot 2023-09-13 at 1 05 32 PM" src="https://github.com/wpeterman/ResistanceGA/assets/89862962/7bc22af9-7dd7-4802-be08-b9895ced4408">

**Comment by wpeterman** [comment]
Not sure why the .rds file is being written, but no other results files. The `@solution` slot has the optimized parameter values. There aren't readily accessible functions to recreate all the outputs that ResistanceGA produces.

**Comment by pdchnsky** [comment]
What should the full.rds files contain? It looks like the full.rds file and the .rds file that I'm getting are the same.

**Comment by wpeterman** [comment]
That is the full .rds. It contains the results of the GA optimization

**Comment by pdchnsky** [comment]
Hello,
This issue was resolved. It turns out that R on the computing cluster was assigning a default temp directory and that was running out of space. ResistanceGA was attempting to write to the temp file but couldn't and then was searching for those files which weren't there. Assigning a user-defined temp file location through R fixed this issue. Thank you!
