### ISSUE TITLE
Doubts about "all_comb"

### ISSUE THREAD

**Issue by martinsc93v** [wpeterman/ResistanceGA#42]
Good evening, my name is Martin, I am an Argentinian researcher and first of all I would like to thank you very much for creating this **wonderful** tool.

I have been using ResistanceGA for a few months now, and I have encountered a major limitation in terms of the time it takes to run the analysis when the maximum iterations are not limited. I know this is to be expected and depends on computational capabilities. I am currently running an analysis of 6 categorical resistance surfaces using the "all_comb" function, to get the final bootstrap analysis as well.

The last analysis without limiting iterations took me more than 3 weeks, so I wanted to ask if there is a reliable way to determine how many iterations are enough to be able to limit it and reduce the time consumption.

If this is not recommended, I wanted to ask if it is possible to perform the analysis in parts. I know I can limit the maximum number of surfaces to be analysed and do it in steps, but that way I wouldn't get the final bootstrap (Or so I believe).

Thank you very much.

**Comment by wpeterman** [comment]
When you say "6 categorical resistance surfaces" do you mean you have 6 binary surfaces each representing a landcover class, or six different categorical surfaces each with >=2 categories? 

I cannot give definitive guidance, but a few suggestions:

- Reduce the max value of `max.cat` in `GA.prep` to 250. This will reduce the parameter space, typically without drastically changing effective resistance distances
- Set `maxiter` to be 150. Usually once 100 iterations is reached, the improvements to the model are extremely trivial. 

It is possible to run the bootstrap analysis on your own after the fact with whatever surfaces you choose (`Resist.boot`). Let me know if you have trouble configuring your data for this function to work.

**Comment by martinsc93v** [comment]
Thank you very much Bill for your quick reply. I do indeed have 6 binary surfaces each representing a land cover class. I will try limiting the iterations to 100 and see how long it takes. Regarding the "Resist.boot" function, I would be interested in being able to use it if I do the analysis separately.

This is my code:

```
GA.inputs <- GA.prep(ASCII.dir = r_new, 
                     resultados.dir = "todos.comb",
                     select.trans = NULL,
                     método = "LL",
                     paralelo = 16)

gdist.inputs <- gdist.prep(n.Pops = length(sp),
                           muestras = sp,
                           respuesta = total_respuesta,
                           método = 'commuteDistance')

all_comb <- all_comb(gdist.inputs = gdist.inputs,
                    results.dir = "D:/Paisaje/Area de trabajo/Proyecto Total/otra prueba"
                    ,GA.inputs = GA.inputs,
                    max.combinación = 6)
```

In order to perform this analysis in a stepwise way and to make better use of the analysis time, I was thinking of using "max.combination = 2" one day, "max.combination = 3-5" another day, and "max.combination = 6-6" another day. That way I would have three outputs, this can then be used to use the Resist.boot?. I don't quite understand what input Resist.boot requires.

I hope I have made myself understood correctly. 

I don't quite understand what input Resist.boot requires.

**Thank you for all your dedication**

**Comment by wpeterman** [comment]
You just need to manually pull everything together to run the function: 

- names of each model (whatever you want to call them)
- Results (effective pairwise distance matrices) of all optimizations as a list. 
- number of parameters estimated in each optimization (can be found in the results folder for the optimization)
The other parameters should be pretty straightforward to figure out
